# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='/media/user_images/'),
        ),
    ]
