# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_user_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
